# Generated by Django 6.0.6 on 2026-06-26 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_category_rename_price_product_discounted_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='orginal_price',
            new_name='original_price',
        ),
    ]
